apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: konflux-kyverno

resources:
  - ../../base

generators:
  - kyverno-helm-generator.yaml

patches:
  - path: kyverno-helm-values-production.yaml
    target:
      kind: HelmChartInflationGenerator
      name: kyverno
